# testing locally without network


Launching on the same computer 
- a client grabbing the display and sending it over the network (stays in the localhost),
- a server displaying it on the host's display


In [1]:
%load_ext autoreload
%autoreload 2

# transforming an array in a set of indices

See http://blog.invibe.net/posts/2016-11-17-finding-extremal-values-in-a-nd-array.html

In [2]:
import numpy as np
x = np.random.randn(4, 3)
print (x)

[[-1.38168387  0.83580852  0.72264732]
 [-0.25487083 -0.05532731  2.10767588]
 [ 0.95254147 -1.28125687  1.44764889]
 [ 1.06668774  0.52170236  0.01030359]]


In [3]:
np.argsort(x.ravel())

array([ 0,  7,  3,  4, 11, 10,  2,  1,  6,  9,  8,  5])

In [4]:
print (np.unravel_index(np.argsort(x.ravel()), x.shape))

(array([0, 2, 1, 1, 3, 3, 0, 0, 2, 3, 2, 1]), array([0, 1, 0, 1, 2, 1, 2, 1, 0, 0, 2, 2]))


just coding the max and min:

In [5]:
n_datapoints=2
x_ = np.argsort(x.ravel())
data_ = np.hstack((x_[:n_datapoints], x_[-n_datapoints:]))
print(data_)

[0 7 8 5]


In [6]:
y = np.zeros_like(x)
#print(y)

In [7]:
y[np.unravel_index(data_[:n_datapoints], x.shape)] = -1
y[np.unravel_index(data_[-n_datapoints:], x.shape)] = 1
print(y)

[[-1.  0.  0.]
 [ 0.  0.  1.]
 [ 0. -1.  1.]
 [ 0.  0.  0.]]


## applying the principle to the retina

In [8]:
%%writefile 2017-05-19_using_eventRetina_testing_local_camera.py
#! /usr/bin/env python3
# -*- coding: utf8 -*-
from __future__ import division, print_function
"""
openRetina : a photoreceptor layer
See https://github.com/laurentperrinet/openRetina
"""
__author__ = "(c) Pierre Albiges, Victor Boutin & Laurent Perrinet INT - CNRS"

from eventRetina import eventRetina
phrs = eventRetina(model=dict(layer='phrs', # label for this layer
                             input=['camera'], # input: can be the camera, noise, a movie (TODO)
                             output=['stream'] # output: can be stream, display, ...
                             ))
phrs.run()

Overwriting 2017-05-19_using_eventRetina_testing_local_camera.py


In [9]:
!chmod +x 2017-05-19_using_eventRetina_testing_local_camera.py 

In [10]:
%%writefile 2017-05-19_using_eventRetina_testing_local_srv.py
"""
openRetina : a basic thalamic layer
See https://github.com/laurentperrinet/openRetina
"""
__author__ = "(c) Victor Boutin & Laurent Perrinet INT - CNRS"

import subprocess
p = subprocess.Popen(['./2017-05-19_using_eventRetina_testing_local_camera.py'])

from eventRetina import eventRetina
camera = eventRetina(model=dict(layer='spikes directly from luminances', # label for this layer
                                 input=['stream'], # input: can be the camera, noise, a movie (TODO)
                                 output=['display'], # output: can be stream, display, capture,...
                                 T_SIM=5, sparseness=0.01))
camera.run()

Overwriting 2017-05-19_using_eventRetina_testing_local_srv.py


In [11]:
!chmod +x 2017-05-19_using_eventRetina_testing_local_srv.py

In [12]:
!ipython3 2017-05-19_using_eventRetina_testing_local_srv.py

]0;IPython: research/PA_INT-internshipNumber of points sent at each frame= 922
spikes directly from luminances Connecting to retina with port 5566
2017-05-19 21:22:08.002 Python[57731:37466416] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/3p/m0g52j9j69z3gj8ktpgg1dm00000gn/T/org.python.python.savedState
/usr/local/lib/python3.6/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated since IPython 4.0. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
spikes directly from luminances is sending request
Before a downscale of 1 dim1 : 720, dim2 : 1280
Using OpenCV
After a downscale of 1, dim1 : 720.0, dim2 : 1280.0
Running out_socket on port:  5566
Number of points sent at each frame= 922
Capture grabbed
phrs Camera client received request b'REQ'
Capture grabbed
spikes directly from luminances is sending request
phrs Came