In [15]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

h, w = 480, 640
sparseness = 0.35
rgb2gray = [0.2989, 0.5870, 0.1140]
output = 'proc_fig.png'

n_datapoints = int(np.ceil(sparseness*h*w)) #Calculating the maximum number of data points according to these paramaters

frame = mpimg.imread('unproc_fig.png')
frame = frame.astype(np.float)          #Convert the data to float (modifications will be easier)
#frame *= np.array(rgb2gray)[np.newaxis, np.newaxis, :]
#frame = frame.sum(axis=-1)              #Sum the data along an axis (negative : count from the last to the first axis)
print(frame)

data_ = np.argsort(frame.ravel()) #Put the data into one dimension and sort it; return the indices (initial position #)
data = np.hstack((data_[:n_datapoints], data_[-n_datapoints:]))

#frame = np.zeros((h, w, 3), dtype = np.uint8)
#frame[:, :, 0][np.unravel_index(data[:n_datapoints], (h, w))] = 255
#frame[:, :, -1][np.unravel_index(data[-n_datapoints:], (h, w))] = 255


#processed_frame = open(output, "w")
#processed_frame = open(output, "r+")
#processed_frame = write(frame)

#img = plt.imshow(255-array*1.)
#plt.savefig('unproc_fig.png', dpi=1000) #dpi=1000 output a high-quality file but greatly increase processing time

#print(frame)

[[[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  ..., 
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  ..., 
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  ..., 
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 ..., 
 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  ..., 
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  ..., 
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  ..., 
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]
  [ 1.  1.  1.  1.]]]
