# testing locally without network


Launching on the same computer 
- a client grabbing the display and sending it over the network (stays in the localhost),
- a server displaying it on the host's display


In [1]:
%load_ext autoreload
%autoreload 2

# transforming an array in a set of indices

See http://blog.invibe.net/posts/2016-11-17-finding-extremal-values-in-a-nd-array.html

In [2]:
import numpy as np
x = np.random.randn(4, 3)
print (x)

[[ 1.65552705 -0.61577166 -0.02550969]
 [-2.1422784  -1.01367995 -1.23886676]
 [ 0.43333037 -0.09706549 -2.36402698]
 [-1.50094623 -0.96434672  0.21962656]]


In [3]:
np.argsort(x.ravel())

array([ 8,  3,  9,  5,  4, 10,  1,  7,  2, 11,  6,  0])

In [4]:
print (np.unravel_index(np.argsort(x.ravel()), x.shape))

(array([2, 1, 3, 1, 1, 3, 0, 2, 0, 3, 2, 0]), array([2, 0, 0, 2, 1, 1, 1, 1, 2, 2, 0, 0]))


just coding the max and min:

In [5]:
n_datapoints=2
x_ = np.argsort(x.ravel())
data_ = np.hstack((x_[:n_datapoints], x_[-n_datapoints:]))
print(data_)

[8 3 6 0]


In [6]:
y = np.zeros_like(x)
#print(y)

In [7]:
y[np.unravel_index(data_[:n_datapoints], x.shape)] = -1
y[np.unravel_index(data_[-n_datapoints:], x.shape)] = 1
print(y)

[[ 1.  0.  0.]
 [-1.  0.  0.]
 [ 1.  0. -1.]
 [ 0.  0.  0.]]


## applying the principle to the retina

In [8]:
%%writefile 2017-05-19_using_eventRetina_testing_local_camera.py
#! /usr/bin/env python3
# -*- coding: utf8 -*-
from __future__ import division, print_function
"""
openRetina : a photoreceptor layer
See https://github.com/laurentperrinet/openRetina
"""
__author__ = "(c) Pierre Albiges, Victor Boutin & Laurent Perrinet INT - CNRS"

from eventRetina import eventRetina
phrs = eventRetina(model=dict(layer='phrs', # label for this layer
                             input=['camera'], # input: can be the camera, noise, a movie (TODO)
                             output=['stream'] # output: can be stream, display, ...
                             ))
phrs.run()

Overwriting 2017-05-19_using_eventRetina_testing_local_camera.py


In [9]:
!chmod +x 2017-05-19_using_eventRetina_testing_local_camera.py 

In [10]:
%%writefile 2017-05-19_using_eventRetina_testing_local_srv.py
"""
openRetina : a basic thalamic layer
See https://github.com/laurentperrinet/openRetina
"""
__author__ = "(c) Victor Boutin & Laurent Perrinet INT - CNRS"

import subprocess
p = subprocess.Popen(['./2017-05-19_using_eventRetina_testing_local_camera.py'])

from eventRetina import eventRetina
camera = eventRetina(model=dict(layer='camera', # label for this layer
                                 input=['stream'], # input: can be the camera, noise, a movie (TODO)
                                 output=['display'], # output: can be stream, display, capture,...
                                 T_SIM=5))
camera.run()

Overwriting 2017-05-19_using_eventRetina_testing_local_srv.py


In [11]:
!chmod +x 2017-05-19_using_eventRetina_testing_local_srv.py

In [12]:
!ipython3 2017-05-19_using_eventRetina_testing_local_srv.py

]0;IPython: research/PA_INT-internshipNumber of points sent at each frame= 77
Connecting to retina with port 5566
2017-05-19 18:41:28.503 Python[55722:37393285] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/3p/m0g52j9j69z3gj8ktpgg1dm00000gn/T/org.python.python.savedState
/usr/local/lib/python3.6/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated since IPython 4.0. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
Duration:  0.0171968936920166
Sending request
Before a downscale of 1 dim1 : 240, dim2 : 320
Using OpenCV
After a downscale of 1, dim1 : 240.0, dim2 : 320.0
Before a downscale of 1 dim1 : 240, dim2 : 320
Using OpenCV
After a downscale of 1, dim1 : 240.0, dim2 : 320.0
Running retina on port:  5566
Number of points sent at each frame= 77
Received request b'REQ'
Capture grabbed
Duration:  2.2571728229522705